apiVersion: v1
kind: ConfigMap
metadata:
  name: github-app-config
  namespace: platform-system
data:
  config.yaml: |
    server:
      address: "127.0.0.1"
      port: 8080
      public_url: "http://127.0.0.1:8080"
    secrets:
      gh-pat: !!env GH_PAT
    runners:
      owner: "flanksource"
      repo:  "karina"
    github:
      v3_api_url: "https://api.github.com/"
      app:
        integration_id: !!env GH_APP_ID
        webhook_secret: !!env GH_WEBHOOK_SECRET
        private_key: !!env GH_PRIVATE_KEY
